replicaCount: 1
image:
  repository: challenge12.azurecr.io/challenge

publicUrl: "challengedevops.duckdns.org"

specs:
  ingress:
    publicUrl: challengedevops.duckdns.org
    port: 3000
  service:
    name: http
    port: 3000
    protocol: TCP
    type: LoadBalancer
