replicaCount: 1
image:
  repository: challenge12.azurecr.io/challenge
  tag: "snapshot"

publicUrl: "challenge.com"

specs:
  ingress:
    publicUrl: challenge.com
    port: 3000
  service:
    name: http
    port: 3000
    protocol: TCP
    type: ClusterIP