replicaCount: 1
image:
  repository: challenge12.azurecr.io/challenge

publicUrl: "challengedevops.duckdns.org"

specs:
  ingress:
    publicUrl: challengedevops.duckdns.org
    port: 80
  service:
    name: http
    port: 80
    protocol: TCP
    type: ClusterIP

env:
  REACT_APP_API_URL: "http://20.96.99.118:8080"